version: 2
jobs:
  build:
    working_directory: ~/kowloonia-parser
    docker:
      - image: circleci/node:6
        environment:
        NODE_ENV: test
    steps:
      - checkout
      - run:
          name: update-yarn
          command: 'sudo npm install -g yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn install deps
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml
